2024-04-10 23:45:08,146 ===== rpi_clock begins =====
2024-04-10 23:45:08,146 Version v5.1
2024-04-10 23:45:08,147 get_config_all: config file rpi_clock.cfg was loaded into memory
2024-04-10 23:45:08,147 get_config_boolean: FLAG_TRACING = False
2024-04-10 23:45:08,147 get_config_color: BG_COLOR_ROOT = MediumPurple2
2024-04-10 23:45:08,147 get_config_color: BG_COLOR_POPUP = green
2024-04-10 23:45:08,147 get_config_color: FG_COLOR_NORMAL = white
2024-04-10 23:45:08,147 get_config_color: FG_COLOR_ALARM = magenta
2024-04-10 23:45:08,147 get_config_string: FORMAT_DATE = %b %d, %Y
2024-04-10 23:45:08,147 get_config_string: FORMAT_TIME = %I:%M %p %Z
2024-04-10 23:45:08,147 get_config_string: TEMP_UNITS = metric
2024-04-10 23:45:08,147 get_config_boolean: FLAG_WINDOWED = False
2024-04-10 23:45:08,147 get_config_int: COUNT_START = 20
2024-04-10 23:45:08,147 get_config_int: REQUEST_TIMEOUT_SEC = 60
2024-04-10 23:45:08,147 get_config_int: SLEEP_TIME_MSEC = 3000
2024-04-10 23:45:08,147 get_config_string: LAT_LONG = 37.2296,-80.4139
2024-04-10 23:45:08,147 get_config_all: done
2024-04-10 23:45:08,147 intialization: done
2024-04-10 23:45:08,187 Will now enter tk_root mainloop
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/root/home/Projects/Personal/rpi_clock/bin/rpi_clock.py", line 363, in display_main_procedure
    display_cur_img.config(image=str_img)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1692, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: image "https://api.weather.gov/icons/land/night/rain_showers,16?size=small" doesn't exist
2024-04-10 23:45:16,021 proc_quit: going to sys.exit(0) next
2024-04-10T23:00:00-04:00
